### ISSUE TITLE
회의 후 수정사항

### ISSUE THREAD

**Issue by myeong-jae-hwi** [ddolmin5155/Android#6]
### 10.23 회의 후 수정사항 

**평균**

- [x] #9

**GPT**
- [x]  대화형을 풀고있는 도중 뒤로가기 버튼 막기
- [x]  뒤로가기 아이콘 변경
- [x]  뒤로가기를 눌렀을 떄 Main Activity 호출
- [x]  전송버튼 공백일때 비활성화

**내정보**
- [x]  내정보 주간 솔루션 삭제 후 차트 키우기
- [x] #7
- [x] #8

**Admin App**
- [x] 총 사용시간

**Comment by YukInhyeok** [comment]
완료
