### ISSUE TITLE
(문제형 맞은 개수 + 대화형 맞은 개수) / (문제형 푼 횟수 + (대화형 푼 횟수 * 5))

### ISSUE THREAD

**Issue by myeong-jae-hwi** [ddolmin5155/Android#9]

**Comment by myeong-jae-hwi** [comment]
예상 알고리즘

1. interactive btn을 눌렀을 때 con_cnt += 1
2. 점수 추출을 했을 때 (현재 value) / 20 을 한 뒤 파이어 베이스에 저장
3. 수식 사용 후 new_val에 저장 후 출력

**Comment by YukInhyeok** [comment]
완료
